// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mcszeyokeqgoxsrmbzit.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1jc3pleW9rZXFnb3hzcm1ieml0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ4OTUxMjksImV4cCI6MjA1MDQ3MTEyOX0.P9bXCWyU72se6smcZVV3YknV0wAIUZEeTlR27HfknXg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);